### PR TITLE
Add permission to support global menu

### PR DESCRIPTION
**Pull request by vroger11**
Global Menu is the globally-shared menu bar of all applications launched in your desktop session. This functionality is available in matte and KDE. An example is available in this video: https://www.youtube.com/watch?v=Tqt9iotv7y8

### CODE REVIEW

**Comment by axtloss** [comment]
I'm honestly not really sure if this is actually needed or should be added. It may be nice to have webcord work with your global menu setup, but it would add another possible security hole in the sandbox for a feature is completely useless for people who do not use a global menu (which to me seems like the majority).

**Comment by vroger11** [comment]
As it is a feature available in the default packages of webcord, I think it must be added to let users have the same experience in the flatpak version. Moreover, this permission is present in the flatpak version of discord (see in https://github.com/flathub/com.discordapp.Discord). Also, in kde it helps to search in the menu bar (like in unity)

I add this permission using flatseal, so it is not a problem to me, but for newbies this can improve their experience

**Comment by axtloss** [comment]
Well this feature isn't really part of webcord, it's more so just the fact that the other packages aren't sandboxes.
Since I still believe that not enough people use global menus (or unity) to warrant an extra permission, it may make more sense to just have some instructions in the readme for how to enable it

**Comment by vroger11** [comment]
Ok no problems, I understand your POV. I agree it should be mentioned in the README.

**Pull request closed without merging**
